apiVersion: v1
kind: Service
metadata:
  name: mytodo-app
  labels:
    app: my-todo-app
spec:
  selector:
    app: my-todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer